# Generated by Django 2.2.7 on 2024-03-22 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buglist',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('In-Progress', 'In-Progress'), ('Testing', 'Testing'), ('Close', 'Close')], default='Open', max_length=19),
        ),
    ]
